language: node_js
node_js:
  - "11"
branches:
  only:
    - master
deploy:
  provider: heroku
  app: boiling-chamber-27922
  api_key:
    secure: uU46CubnqrOpW6kpX/K9Htmfv116iWqt68eZUNSqwJs0/R1bIG+e6zjPH3nLgG9qnu4E7SzI9fDfNI1QPj/GpjqIHnIwKFs/cQzfIKaCvg40AfTMk4PmYLBMYpSxyYoEjF9+HOjviHbI5mWlsQ4R5Nxw9nEOWRyYeDPon5KzTkb3vXRIKwRt/GXcAn54l2lqJmqgGWEhfRdjA5jqYTFpKvvUVmJG51klh4KpznQiCZ0qHeGr4hvh3XFCAekQl+opsKBzAqoYhzAPYYl90KHaZ44BKRRpUfa8S+B5LdRyP5pnD5Q9akskZhuI7CZ4wsuL+cVw6Q5hopRu90tyB6qBnKL25rFP90xepZ4RafsRqvH/oKnXGgE8TqnWV8vmvUqeFo8alksDeL0fUL2l9GapFakHQ28q4LbfOahUtaOnSHrDwpLW6ofBXGMbDP4ei6YCnzqhtDSfKI6PZlF7oAZsSRSsVdQ0AnCznirY+RVff4GrX3Ef7xpV35VPZF9EEyQmafnwaYyNCmeVHN7YlqryCSuHbN6AP1mJvyMZE2RFKKNCT2WtXvnZo6Jo+5qUYgrgo+0d3MK9Y9UWOcRB0qHgySaATwuajOdjGCyb/gdHpzE1EBx7oCx0beGka2aRRqMpoYosZd+SVty0k/PPe0Yf90ifhHdZgs6433VRxUYVuTE=
